name: Ruleset10_Override_Housing_Purpose
description: Contains rule for overriding housing purpose
version: '1.2'
author: nathan+business@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: ruleset10overridehousingpurpose
  parentArtefactID: westpacbusiness
  buildSystem: wheel
  author: null
  createdAt: '2024-05-23 00:43:52'
pipelines:
  pipelines/test_rule:
    name: Test_OverrideHousingPurpose
    description: Ruleset that includes rules for overriding housing purpose.
    author: nathan+business@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-23 00:43:52'
    datasets:
      inputs:
      - datasets/sample_data
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/sample_data:
    name: housingpurposeid_sampledata
    description: ''
    author: nathan+business@prophecy.io
    createdAt: '2024-05-23 01:18:25'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan+business@prophecy.io
        createdAt: '2024-05-23 01:18:25'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/AddRule:
      name: AddRule
      category: Transform
      subCategory: ''
      description: null
      author: nathan+business@prophecy.io
      mode: batch
      files:
      - westpacbusiness_ruleset10overridehousingpurpose/gems/AddRule.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-05-23 00:59:53'
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-23 00:43:52'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/Override_Housing_Purpose:
      name: Override_Housing_Purpose
      description: Rule to override housing purposes
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-23T00:43:52.974443Z'
  name: plibMaven
  version: 7.1.100
  id: '26193071'
  createdAt: '2024-05-23T00:43:52.974443Z'
  type: plibMaven
- modifiedAt: '2024-05-23T00:43:52.974443Z'
  name: plibPypi
  version: 1.8.23
  id: '1557297722'
  createdAt: '2024-05-23T00:43:52.974443Z'
  type: plibPypi
projectDependencies:
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-23 00:43:30'
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-23 00:43:30'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
