name: Ruleset10_Override_Housing_Purpose
description: Contains rule for overriding housing purpose
version: '2.1'
author: nathan+business@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: ruleset10overridehousingpurpose
  parentArtefactID: westpacbusiness
  buildSystem: wheel
  author: null
  createdAt: '2024-05-23 00:43:52'
pipelines:
  pipelines/test_rule:
    name: Test_OverrideHousingPurpose
    description: Ruleset that includes rules for overriding housing purpose.
    author: nathan+business@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-23 00:43:52'
    datasets:
      inputs:
      - datasets/sample_data
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/Test_RiskAssetClassSegmentation:
    name: Test_RiskAssetClassSegmentation
    description: Test Risk Asset Class Segmentation Rule
    author: nathan+business@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-23 21:10:54'
    datasets:
      inputs:
      - datasets/riskassetclass_sampledata
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/sample_data:
    name: housingpurposeid_sampledata
    description: ''
    author: nathan+business@prophecy.io
    createdAt: '2024-05-23 01:18:25'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan+business@prophecy.io
        createdAt: '2024-05-23 01:18:25'
  datasets/riskassetclass_sampledata:
    name: riskassetclass_sampledata
    description: ''
    author: nathan+business@prophecy.io
    createdAt: '2024-05-23 21:13:50'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan+business@prophecy.io
        createdAt: '2024-05-23 21:13:50'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/AddRule:
      name: AddRule
      category: Transform
      subCategory: ''
      description: null
      author: nathan+business@prophecy.io
      mode: batch
      files:
      - westpacbusiness_ruleset10overridehousingpurpose/gems/AddRule.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-05-23 00:59:53'
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-23 00:43:52'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/RiskAssetClassSegmentation:
      name: RiskAssetClassSegmentation
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Override_Housing_Purpose:
      name: Override_Housing_Purpose
      description: Rule to override housing purposes
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Override_EFS_Rule_Id:
      name: Override_EFS_Rule_Id
      description: This overrides EFS Rule ID based on certain conditions
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-23T21:10:57.805406Z'
  name: plibMaven
  version: 7.1.100
  id: '757731159'
  createdAt: '2024-05-23T21:10:57.805375Z'
- type: plibPypi
  modifiedAt: '2024-05-23T21:10:57.805442Z'
  name: plibPypi
  version: 1.8.23
  id: '1307381560'
  createdAt: '2024-05-23T21:10:57.805433Z'
projectDependencies:
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-23 00:43:30'
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-23 00:43:30'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
